language: go

arch:
  - amd64
  - ppc64le

os:
  - linux
  - windows

go:
  - "1.10.x"
  - "1.x"
  - master

# golang master is not available for Windows builds for some reason
matrix:
  exclude:
    - os: windows
      go: master

go_import_path: github.com/cloudflare/gokey
